Update Nginx Proxy Manager init script

diff --git a/.github/workflows/DebianNginxProxyManager.yml b/.github/workflows/DebianNginxProxyManager.yml
--- a/.github/workflows/DebianNginxProxyManager.yml
+++ b/.github/workflows/DebianNginxProxyManager.yml
@@ -38,34 +38,32 @@ jobs:
             cat $EPS_BASE_URL/apps/$EPS_APP_NAME/config.sh
             sed -i 's|EPS_SERVICE_DATA=.*|EPS_SERVICE_DATA='\''#!/bin/sh\n### BEGIN INIT INFO\n# Provides:npm\n# Required-Start:$network $local_fs $remote_fs\n# Required-Stop:$network $local_fs $remote_fs\n# Default-Start:2 3 4 5\n# Default-Stop:0 1 6\n# Short-Description:Start/stop Nginx Proxy Manager\n### END INIT INFO\ncase "$1" in\n  start)\n    echo "Starting Nginx Proxy Manager..."\n    mkdir -p /tmp/nginx/body /data/letsencrypt-acme-challenge\n    NODE_ENV=production /usr/local/bin/node /app/index.js --abort_on_uncaught_exception --max_old_space_size=250 &\n    ;;\n  stop)\n    echo "Stopping Nginx Proxy Manager..."\n    killall node\n    ;;\n  *)\n    echo "Usage:/etc/init.d/npm {start|stop}"\n    exit 1\n    ;;\nesac\nexit 0'\''|' $EPS_BASE_URL/apps/$EPS_APP_NAME/config.sh
             
-            cat << 'EOF' > replacement.txt
-            #!/bin/sh
-            ### BEGIN INIT INFO
-            # Provides:          npm
-            # Required-Start:    $network $local_fs $remote_fs
-            # Required-Stop:     $network $local_fs $remote_fs
-            # Default-Start:     2 3 4 5
-            # Default-Stop:      0 1 6
-            # Short-Description: Start/stop Nginx Proxy Manager
-            ### END INIT INFO
-            case "$1" in
-                start)
-                    echo "Starting Nginx Proxy Manager..."
-                    mkdir -p /tmp/nginx/body /data/letsencrypt-acme-challenge
-                    NODE_ENV=production /usr/local/bin/node /app/index.js --abort_on_uncaught_exception --max_old_space_size=250 &
-                    ;;
-                stop)
-                    echo "Stopping Nginx Proxy Manager..."
-                    killall node
-                    ;;*)
-                    echo "Usage:/etc/init.d/npm {start|stop}"
-                    exit 1
-                    ;;
-            esac
-            exit 0
-            EOF
+            echo '#!/bin/sh' > replacement.txt
+            echo '### BEGIN INIT INFO' >> replacement.txt
+            echo '# Provides:          npm' >> replacement.txt
+            echo '# Required-Start:    $network $local_fs $remote_fs' >> replacement.txt
+            echo '# Required-Stop:     $network $local_fs $remote_fs' >> replacement.txt
+            echo '# Default-Start:     2 3 4 5' >> replacement.txt
+            echo '# Default-Stop:      0 1 6' >> replacement.txt
+            echo '# Short-Description: Start/stop Nginx Proxy Manager' >> replacement.txt
+            echo '### END INIT INFO' >> replacement.txt
+            echo 'case "$1" in' >> replacement.txt
+            echo '    start)' >> replacement.txt
+            echo '        echo "Starting Nginx Proxy Manager..."' >> replacement.txt
+            echo '        mkdir -p /tmp/nginx/body /data/letsencrypt-acme-challenge' >> replacement.txt
+            echo '        NODE_ENV=production /usr/local/bin/node /app/index.js --abort_on_uncaught_exception --max_old_space_size=250 &' >> replacement.txt
+            echo '        ;;' >> replacement.txt
+            echo '    stop)' >> replacement.txt
+            echo '        echo "Stopping Nginx Proxy Manager..."' >> replacement.txt
+            echo '        killall node' >> replacement.txt
+            echo '        ;;*)' >> replacement.txt
+            echo '        echo "Usage:/etc/init.d/npm {start|stop}"' >> replacement.txt
+            echo '        exit 1' >> replacement.txt
+            echo '        ;;' >> replacement.txt
+            echo 'esac' >> replacement.txt
+            echo 'exit 0' >> replacement.txt
 
-            sed -i "/EPS_SERVICE_DATA=/c\EPS_SERVICE_DATA=\"$(<replacement.txt)\"" config.sh
+            sed -i "/EPS_SERVICE_DATA=/c\EPS_SERVICE_DATA=\"\$(<replacement.txt)\"" $EPS_BASE_URL/apps/$EPS_APP_NAME/config.sh
 
 
             export EPS_APP_CONFIG=${EPS_APP_CONFIG:-$(cat $EPS_BASE_URL/apps/$EPS_APP_NAME/config.sh)}
